language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
env:
  global:
  - secure: v0Pb49+1iWYv5DVMGEe4LaJC78xhXpoTieNONvwrpkXYoDlz8UXkHnaI2sCj4uArFfljCYIqCvB9lsx8WNeoP8rOr5rsktwFsAxgzLoRSbFS8N9Qqo3FrjvT/6la7/XXdepIvExcd9YtMt8MYPt3vJSBtnz9QId41VQ6pKd1uo8HfYlhr2YTIIJ7R3Sj7THvBS56P3JzItjxWPpPucJR5tky1HHS9pNsI2lW6VRNv1/s22S8+SZzle3PwRCMHAtK2AAFQ/9qmU1qiDWBv/GwVa6u6fgGk2vJ8N030098B7yMILxbmhkRM/9RrcFn5JBcRshTDWT+PSENQp4ge60NCZx8atM79eCH8IFpfPhkjPywdJZkscUoXS6+PZJqcDGo4Mb9DznWwbIin3+GMrGrcYReopM8r9Neh9p/B/i7+VQVv9LHC/FXaDQQWunnxQHgfeWPG7fKpkBGTkzyikkdsS7QfClm1O+nIMYf6hACXtX8sAY57hoIh1pHGe9R/iEVn9byQ140LZ4akh4Y+DQvuAJGIoSnRsFts3U0akgzc0Gj+EmQTkVHakJvua+xsoaQmtNpSzj4G19aoCeGe3t2t/ztZv1/sVJQB8QwHZEcLjcVTWNqNCBJIVglfgiUd93CMNOUBOv8JdUV4eUYeLPJjaHV/K22DNynEqdGAR24Enw=
  - secure: KKbq4VATJ6zpsykmbBTrXdLkK5pDIkdXtPjOBpeQ/xOop3DlMar0NVFNLuVLC65zfpJBGq18Ax+/Jb7HJK70j4t2aSSn/Xtls5V7oT4J4giZIF8Zu6SFy0R67gb28zT2Z42BY2bKSGRWpwPzN1Bv2DLR5VM/uqLyNoRNiDnDTNvdpWH9Hv/3V/UwCCZYJHkEhq5WcbsTlDeqfDa/keQ3p+aFFhnk6h+npvC/J6iyU0MKguk5msrlpPtTf4Vg4BOz4/eObt4Rtq4tFhBCK57LAvhmSxCk7wWCAMP4b8PcMstewF+YRo8STeQ3uv96tFsRoxBCGVHr+9B/fwBJE//WAKSYVNcbNrZsUAARIpLxj0XYAmWFNZfRHmRznD8G0uZ/f92kOkNGbsjFOMHVrtcScH2aKpMzL+7KG/pjUdaHpRQ0OVLB3+dfMkLjmBFP+Po6NpKYu4N8Vw3qOz95oZD4I6f7Bi2XnmVOWmtbCHH9Iwm5d+mNfgZCmhCzweaKJaWR7zdE+aIBre6BoJ/sZYBsfcnjgscZgZiG8woJlqFsKMTLDZpOacgYLOFd74MwL1ZXbZbvoVFP6VM0V43S33wcOYcl/E+V+j6qzVR1xFSNI14Uq2WbHerdBKmZw97JRlwfhTdog4xbJknB+1Dq1Ve70UFVaHEIw8gok17sc1u3Zss=
  - secure: qcCscMhBpRoK2HuVbm8AZG3cCyIg/O2ro90ChEAEKh3XoMe6JB/Zb3FvzEO3EfdgDJxAbKxENlMeLNcPjEDHw85a16kkLby8i5wW7dsAMo6rSUHb9Y763jwQ1h8dSmCD2uObUPJIRLuBaXMdfUJfg4K8fdDEDQW/qAU9YOmue51HbuJ7bsXDPQpje0ImK5Uv00/S8pphU7c5iuAS1wXdySvQbUuyZGMUvF4kZow3iIA8Sa+8gTW5xFG/xouCyOy7wHGDQgGB0dSUwV4kv0ETuvfW1hVc5RKNDEQqlmQdofaci+tKK73UQBlSLzydjqRHxdhAADaZAr0grJ0O/USMRxi02TifYGIUNZmAYZiymNpI8ykK6H1yyADEAy/7oVDcecP3/dFxD+pfMpctl+UJCUemYmz570CuTaL+fKqEGWF+Pez5f1b7BxcI4VBTlxpNakl7FCp6n2ndRm4d90p5Xr/111NXhC0queSFkbhDNZaJvF9JzVGZ+0xWigdZGlmVY3/Xa9z3YAbxJ2Tw2wHHL/Mtih8BKPMp2pzb+ZQ7q1auS+0gyFDCJHZHaO815KC9wgaZe3wYbHzC/EzcOGnjTFizant0APat7nCS3QR7wac/FbLLL2PSO7RgpsToXp1Oz15+SX2Y44mfEKXmZNsJ93zfwY+/06HTS9cZarrThT0=
cache:
  directories:
  - "$UNITY_DOWNLOAD_CACHE"
before_install:
- chmod a+x ./travis-build/*.sh
install:
- cat /etc/hosts
- "./travis-build/install-unity.sh"
script:
- "./travis-build/build.sh"
- "./travis-build/run-tests.sh"
- "./travis-build/clean-up.sh"
